[phases.setup]
nixpkgs = ["python311", "playwright"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "playwright install chromium"
]

[start]
cmd = "playwright install chromium && python app.py"
